name: Run pre-commit

on:
  workflow_dispatch:


jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install requirements
        run: python -m pip install -r requirements-dev.txt
        shell: bash
      
      - name: Lists installed packages
        run: python -m pip freeze
